### ISSUE TITLE
perform a simulation with walls and rigid objects

### ISSUE THREAD

**Issue by nirrin-analytics** [cselab/Mirheo#104]
Is there way to perform a simulation in which there are rigid objects, and walls from which the rigid objects are excluded? When I attempt to perform such a simulation I get an error with the line:

`u.setWall(wall, pv_rigid) `

where pv_rigid is a RigidObjectVector. The error is:

`PVs should only be attached to walls with the primary cell-lists! Invalid combination: wall sdfwall, pv spheres`

 If I remove this line, the simulation runs, but the rigid objects can penetrate the walls, is there anyway to attach the RigidObjectVector to the wall?

**Comment by amlucas** [comment]
Hello @nirrin-analytics , in Mirheo the [setWall](https://mirheo.readthedocs.io/en/latest/user/coordinator.html#_mirheo.mirheo.setWall) method is meant to bounce back the particles (not the full object vectors) from walls, thus we prevent that to be working with object vectors.
What you can do to prevent the objects to penetrate walls is to make use of [wall repulsion plugin](https://mirheo.readthedocs.io/en/latest/user/coordinator.html#_mirheo.mirheo.setWall).

**Comment by nirrin-analytics** [comment]
Thank you, that works!
